### ISSUE TITLE
existance of objects block deserializing the whole string

### ISSUE THREAD

**Issue by InstanceOfMichael** [naholyr/js-php-unserialize#9]
Seems like it would be more logical to return this:

```
{
    data1: "...",
    data2: "...",
    data3: "...",
    unexpectedObject:"[Object PHPClass]",
}
```
instead of throwing an exception and blocking access to the other serialized data.

**Comment by naholyr** [comment]
Two different things here:
- Support for objects will exist when project is revived and #11 is fixed right next
- Continuation after a parse error should not be something to try imho, if string is corrupted you cannot assume anything about what you already parsed or what is still to be parsed

Closed as dup #11 and/or wontfix ;)
